
BFLAGS=-O3 -fcfa-arithmetic -q -lib-dir $(BOOTLIBDIR)
BOOTFLAGS=
BFEATUREFLAGS=-srfi enable-pcre
LDSTRIPFLAGS=

SCRIPTEXTENSION=
C_OBJ_EXTENSION=o

APIS=pthread fthread srfi18 ssl sqlite web multimedia mail calendar pkgcomp pkglib text srfi1 crypto openpgp csv upnp libuv gstreamer phidget alsa wav flac mpg123 phone avahi srfi27 packrat
NOAPIS=


BFLAGS=-O3 -fcfa-arithmetic -q -lib-dir $(BOOTLIBDIR)
BOOTFLAGS=
BFEATUREFLAGS=-srfi enable-pcre
LDSTRIPFLAGS=

SCRIPTEXTENSION=
C_OBJ_EXTENSION=o

APIS=pthread fthread srfi18 ssl sqlite web multimedia mail calendar pkgcomp pkglib text srfi1 crypto openpgp csv upnp libuv gstreamer phidget alsa wav flac mpg123 phone avahi srfi27 packrat
NOAPIS=

